### ISSUE TITLE
Refactor `Block` view into simpler `Border` view/widget

### ISSUE THREAD

**Issue by Philipp-M** [Philipp-M/trui#4]
I think the current code of `Block` is more complex than it needs to be.

I'm thinking about doing something like:

```rust
"Button"
    .borders((Borders::Vertical, Style::fg(Color::Red)))
    .borders((Borders::Horizontal, Style::bg(Color::Green), BorderKind::Rounded))
```
(Could also well be done directly via `BorderStyle { kind: BorderKind::Rounded, ...Default::default() }` but this is probably more verbose than it needs to be)

Whereas each `.borders()` would result in a new view/widget.

**Comment by Philipp-M** [comment]
Though, especially "edge" cases (and I really mean corners) will be interesting to handle here. Maybe this could be configurable with another attribute within the styles given to the borders...

**Comment by Philipp-M** [comment]
I think the `Borders` bitflags can be extended to include the 4 corners and just be bit ored together, then we don't need extra attributes.

Something like:
```rust
/// Show the top border
const TOP = 0b00000001;
/// Show the top right corner
const TOP_RIGHT = 0b00010000;
const TOP_LEFT = 0b00100000;
const TOP_WITH_CORNERS = TOP | TOP_RIGHT | TOP_LEFT;
```

(Maybe with different naming, because `TOP | RIGHT` and `TOP_RIGHT` kinda looks ambiguous)

**Comment by zoechi** [comment]
What happens if a border flag is false? Is no border rendered while it still takes up space or does it not even take up space?

**Comment by Philipp-M** [comment]
Good question. I'd say it doesn't take any space and is basically a dummy wrapper i.e. has the same layout effect as no `.borders()` at all around it, so that it is consistent (since there's already `Borders::ALL`).

(So not particularly useful, but I expect some cases in the API that don't make sense).

**Comment by zoechi** [comment]
This means a border can only be zero or one character high/broad, but not 2? 
It's probably not too common to have 2 characters wide/high borders in TUI. There might be cases like with added label or similar.

**Comment by Philipp-M** [comment]
Currently...

Since borders are very much mono-spaced unicode characters (very much taken/inspired directly from ratatui).
If it makes sense for some reason to have bigger borders, that can probably added (in the future).

But when it's just about spacing, I think it should be done via a layout (modifier) widget like padding.

**Comment by zoechi** [comment]
I was thinking a bit about that, but haven't come to a conclusion.
I would usually try to avoid lines and just have the background colored differently. That should be easy enough with the current design.  
A bit fancier would be to allow a label in the border (like a group caption) and perhaps colour gradients.
Then I thought about borders with lines AND labels might want a line above or below the label like, which would lead to width of more than 1.

```
     _______
 ___/ Label \___________________
|                              |
|                              |
...
```

That's just brainstorming. There is no need to implement this now of course and it could even be a different widget like a Group.

Spacing should definitely be a different widget (margin, padding),
but with border it wasn't so clear to me where to draw the line.

The video at the top of the readme.md of this project shows how I would like a terminal app to look like https://github.com/directvt/vtm for some inspiration 😉

**Comment by Philipp-M** [comment]
> There might be cases like with added label or similar.

Probably missed that.

I think that this should probably be its own widget. I think I rather like to have a lot of simple building blocks specific to one use case (such as a label/group) than a "does-everything-component" (I think that's also part of the reason, why I'd like to move away from something like `Block` to `Borders`).

But as always it probably depends on the exact use-case, and e.g. how much code would be shared etc. This can possibly also be implemented within the `border` widget itself, I don't know...

Yeah something like vtm or even fancier [notcurses](https://github.com/dankamongmen/notcurses) is probably the long-term goal. But I first like to focus on stuff where Xilem may also profit from (mainly API, styling, layout etc. i.e. researching the UI problem space in Rust, and putting all this into practice to see how well it really works).

**Comment by zoechi** [comment]
I fully agree. I also do not want to build vtm or notcurses, but rather something that can be used to build vtm or notcurses.

Didn't know about notcurses.

I'm just throwing ideas. There is no desire to implement all the fancy stuff right now. I only try to find the patterns that might be a good fit for basic building blocks.

**Comment by zoechi** [comment]
I looked a bit into notcurses. Quite interesting. It looks like a possible alternative backend instead of crossterm.

**Comment by Philipp-M** [comment]
Maybe, I don't see that as an immediate priority currently though (TUI will never be as good as a real GUI anyway). I would like to avoid having all the ugliness of C++ build tooling around (at a quick glance it at least requires CMAKE). Would be nice to stay Rust only which makes it quite portable and creates less headaches...

Maybe RIIR notcurses^^.

**Comment by zoechi** [comment]
Right, that would only be an optimization step when everything else works great and we run out of work ;-)
